name: metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: output
          committer_message: "Update metrics"
          base: header, activity
          plugin_languages: yes
          plugin_languages_analysis_timezone: Asia/Karachi
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_threshold: 0%
          plugin_languages_details: lines
          config_timezone: Asia/Karachi
          config_display: large
